In [2]:
import tensorflow as tf

tf.__version__

'1.15.0'

In [6]:
a = tf.constant(1.0)
b = tf.constant(2.0)
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])

print(a)
print(a + b)
print(c)

sess = tf.compat.v1.Session()
print(sess.run([a, b]))
print(sess.run(c))
print(sess.run([a + b]))
print(sess.run(c+1.0))
sess.close()


Tensor("Const_9:0", shape=(), dtype=float32)
Tensor("add_5:0", shape=(), dtype=float32)
Tensor("Const_11:0", shape=(2, 2), dtype=float32)
[1.0, 2.0]
[[1. 2.]
 [3. 4.]]
[3.0]
[[2. 3.]
 [4. 5.]]


In [8]:
import tensorflow as tf

a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(4)

calc1_op = a + b * c
calc2_op = (a + b) * c

sess = tf.Session()
res1 = sess.run(calc1_op)
print(res1)
res2 = sess.run(calc2_op)
print(res2)
sess.close()

14
20


In [9]:
import tensorflow as tf

# 플레이스홀더 노드 정의
a = tf.placeholder(tf.float32) 
b = tf.placeholder(tf.float32) 
c = a + b

# 세션 (session) 을 만들고 플레이스홀더 노드를 통해 값 입력받음
sess = tf.Session()
print(sess.run(c, feed_dict={ a: 1.0, b: 3.0 })) 
print(sess.run(c, feed_dict={ a: [1.0, 2.0], b: [3.0, 4.0] })) 
# 세션 close
sess.close()


4.0
[4. 6.]


In [10]:
import tensorflow as tf

# 플레이스홀더 정의하기 --- (※1)
a = tf.placeholder(tf.int32, [3]) # 정수 자료형 3개를 가짂 배열
#a = tf.placeholder(dtype=tf.float32, shape=[None, 3]) # 2차원 구조로 정의
# 배열을 모든 값을 2배하는 연산 정의하기 --- (※2)
b = tf.constant(2)
x2_op = a * b

# 세션 시작하기 --- (※3)
sess = tf.Session()
# 플레이스홀더에 값을 넣고 실행하기 --- (※4)
r1 = sess.run(x2_op, feed_dict={ a:[1, 2, 3] })
print(r1)
r2 = sess.run(x2_op, feed_dict={ a:[10, 20, 10] })
print(r2)


[2 4 6]
[20 40 20]


In [13]:
import tensorflow as tf

# 값이 업데이트되는 변수노드 정의
W1 = tf.Variable(tf.random.normal([1])) 
b1 = tf.Variable(tf.random.normal([1]))
W2 = tf.Variable(tf.random.normal([1, 2])) 
b2 = tf.Variable(tf.random.normal([1, 2]))

# 세션 생성
sess = tf.Session()
# 변수노드 값 초기화. 변수노드를 정의했다면 반드시 필요함
sess.run(tf.global_variables_initializer()) 

for step in range(3):
    W1 = W1 - step 
    b1 = b1 - step
    W2 = W2 - step 
    b2 = b2 - step
    print("step = ", step, ", W1 = ", sess.run(W1), ", b1 = ", sess.run(b1))
    print("step = ", step, ", W2 = ", sess.run(W2), ", b2 = ", sess.run(b2))
sess.close()

step =  0 , W1 =  [1.0785018] , b1 =  [-3.2560894]
step =  0 , W2 =  [[1.0041311 1.2518039]] , b2 =  [[ 0.960916  -1.1021158]]
step =  1 , W1 =  [0.07850182] , b1 =  [-4.256089]
step =  1 , W2 =  [[0.00413108 0.25180387]] , b2 =  [[-0.03908402 -2.1021156 ]]
step =  2 , W1 =  [-1.9214982] , b1 =  [-6.256089]
step =  2 , W2 =  [[-1.9958689 -1.7481961]] , b2 =  [[-2.039084  -4.1021156]]


In [19]:
import tensorflow as tf

# feeding 값 선언
input_data = [1,2,3,4,5]
# placeholder 변수 선언
x = tf.placeholder(dtype=tf.float32)
# W = 2라는 값 선언
W = tf.Variable([2],dtype=tf.float32)
y = W * x

sess = tf.Session()
# 변수 초기화 코드를 세션에 젂달핚다.
sess.run(tf.global_variables_initializer())
# y 그래프에 input_date feeding 하면서 세션 실행핚다.
result = sess.run(y,feed_dict={x:input_data})
print(result)

[ 2.  4.  6.  8. 10.]


In [20]:
import tensorflow as tf

# 상수 정의하기 --- (※1)
# name을 이용해서 별칭 부여도 가능
a = tf.constant(120)
b = tf.constant(130)
c = tf.constant(140)

# 변수 정의하기 --- (※2)
# 변수 v를 정의하고 초기치 0을 저장
v = tf.Variable(0) 

# 데이터 플로우 그래프 정의하기 --- (※3)
calc_op = a + b + c
assign_op = tf.assign(v, calc_op)

# 세션 실행하기 --- (※4)
sess = tf.Session()
# tf.global_variables_initializer() 
# 메소드를 사용하여 세션에 초기화 연산을 수행해야 하며, 변수에 메모리를 핛당하고 초기값을 설정하는 역핛을 핚다.
sess.run(tf.global_variables_initializer())
sess.run(assign_op)
# v의 내용 출력하기 --- (※5)
print( sess.run(v) )


390


# BMI

In [22]:
import pandas as pd
import numpy as np
import tensorflow as tf

# 키, 몸무게, 레이블이 적힌 CSV 파일 읽어 들이기 --- (※1)
csv = pd.read_csv("../bmi.csv")
# 데이터 정규화 --- (※2)
csv["height"] = csv["height"] / 200
csv["weight"] = csv["weight"] / 100

# 레이블을 배열로 변홖하기 --- (※3)
# - thin=(1,0,0) / normal=(0,1,0) / fat=(0,0,1)
bclass = {"thin": [1,0,0], "normal": [0,1,0], "fat": [0,0,1]}
csv["label_pat"] = csv["label"].apply(lambda x : np.array(bclass[x]))


In [27]:
csv

height  weight   label  label_pat
0       0.710    0.62     fat  [0, 0, 1]
1       0.710    0.73     fat  [0, 0, 1]
2       0.885    0.61  normal  [0, 1, 0]
3       0.935    0.48    thin  [1, 0, 0]
4       0.765    0.60     fat  [0, 0, 1]
...       ...     ...     ...        ...
19995   0.610    0.58     fat  [0, 0, 1]
19996   0.965    0.69  normal  [0, 1, 0]
19997   0.965    0.37    thin  [1, 0, 0]
19998   0.975    0.51    thin  [1, 0, 0]
19999   0.815    0.67  normal  [0, 1, 0]

[20000 rows x 4 columns]

In [23]:
# 테스트를 위핚 데이터 분류 --- (※4)
test_csv = csv[15000:20000]
test_pat = test_csv[["weight","height"]]
test_ans = list(test_csv["label_pat"])

# 플레이스홀더 선언하기--- (※5) 
x = tf.placeholder(tf.float32, [None, 2]) # 키와 몸무게 데이터 넣기.2차원구조 ※※※(row, col)※※※
y_ = tf.placeholder(tf.float32, [None, 3])

# 변수 선언하기 --- (※6)
W = tf.Variable(tf.zeros([2, 3])); # 가중치 height, weight 두개니까.??..
b = tf.Variable(tf.zeros([3])); # 바이어스 

# 소프트맥스 회귀 정의하기 --- (※7)
y = tf.nn.softmax(tf.matmul(x, W) + b) 

# 모델 훈련하기 --- (※8)
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=y, labels=y_)) #(예측값y, 정답y_)
# GradientDescentOptimizer : 경사하강법으로 손실 함수를 최소화하는 모델 파라미터를 찾기 위해 사용
# 0.01은 학습률을 의미
optimizer = tf.train.GradientDescentOptimizer(0.01) # w와 b를 자동으로 설정함
train = optimizer.minimize(cross_entropy)


In [24]:
# 정답률 구하기
predict = tf.equal(tf.argmax(y, 1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(predict, tf.float32)) # tf.cast() : 캐스트 연산에 사용


In [28]:
# 세션 시작하기
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 변수 초기화하

# 학습시키기
for step in range(15000):
    i = (step * 100) % 15000
    rows = csv[1 + i : 1 + i + 100]
    x_pat = rows[["weight","height"]]
    y_ans = list(rows["label_pat"])
    fd = {x: x_pat, y_: y_ans}
    sess.run(train, feed_dict=fd)
    if step % 500 == 0:
        cre = sess.run(cross_entropy, feed_dict=fd)
        acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})
        print("step=", step, "cre=", cre, "acc=", acc)

# 최종적인 정답률 구하기
acc = sess.run(accuracy, feed_dict={x: test_pat, y_: test_ans})
print("정답률 =", acc) 


step= 0 cre= 1.098595 acc= 0.3242
step= 500 cre= 1.0949001 acc= 0.3684
step= 1000 cre= 1.0968362 acc= 0.3684
step= 1500 cre= 1.0890875 acc= 0.3684
step= 2000 cre= 1.0854574 acc= 0.3684
step= 2500 cre= 1.0907798 acc= 0.3684
step= 3000 cre= 1.0794799 acc= 0.3772
step= 3500 cre= 1.0763575 acc= 0.4024
step= 4000 cre= 1.082489 acc= 0.433
step= 4500 cre= 1.0693377 acc= 0.4796
step= 5000 cre= 1.0670123 acc= 0.5142
step= 5500 cre= 1.0734549 acc= 0.5468
step= 6000 cre= 1.058941 acc= 0.5828
step= 6500 cre= 1.0574982 acc= 0.6054
step= 7000 cre= 1.0642852 acc= 0.6246
step= 7500 cre= 1.0485251 acc= 0.6442
step= 8000 cre= 1.0479634 acc= 0.6528
step= 8500 cre= 1.0552124 acc= 0.659
step= 9000 cre= 1.038259 acc= 0.6674
step= 9500 cre= 1.0385478 acc= 0.6726
step= 10000 cre= 1.0463612 acc= 0.6774
step= 10500 cre= 1.0282755 acc= 0.6812
step= 11000 cre= 1.02937 acc= 0.683
step= 11500 cre= 1.0378207 acc= 0.6846
step= 12000 cre= 1.018677 acc= 0.6868
step= 12500 cre= 1.0205234 acc= 0.6872
step= 13000 cre= 1.0

# MNIST (손글씨 숫자 0~9)

In [29]:
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np


In [30]:
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
print(f"\ntrain image shape = {np.shape(mnist.train.images)}")
print(f"train label shape = {np.shape(mnist.train.labels)}")
print(f"test image shape = {np.shape(mnist.test.images)}")
print(f"test label shape = {np.shape(mnist.test.labels)}")


Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py fr

In [31]:
# 신경망 구조 및 하이퍼 파라미터 설정
learning_rate = 0.1 #학습율
epochs = 100 #반복횟수
batch_size = 100 #한번에 입력으로 주어지는 mnist 데이터 수
input_nodes = 784 #입력층 노드 개수
hidden_nodes = 100 #은닉층 노드 개수
output_nodes = 10 #출력층 노드 개수


In [35]:
# 입력과 출력을 위핚 플레이스홀더(placeholder) 정의
X = tf.placeholder(tf.float32, [None, input_nodes])
T = tf.placeholder(tf.float32, [None, output_nodes])

# 가중치와 바이어스 노드 정의
W2 = tf.Variable(tf.random_normal([input_nodes, hidden_nodes]))
b2 = tf.Variable(tf.random_normal([hidden_nodes]))
W3 = tf.Variable(tf.random_normal([hidden_nodes, output_nodes]))
b3 = tf.Variable(tf.random_normal([output_nodes])) 


In [36]:
# 피드포워드를 수행하는 노드 정의
Z2 = tf.matmul(X, W2) + b2 # 은닉층 선형회귀 값 Z2 np.dot() 함수와 동일핚 기능 구현
A2 = tf.nn.relu(Z2) # 은닉층 출력 값 A2 sigmoid 함수가 대싞 relu 함수 사용
Z3 = logits = tf.matmul(A2, W3) + b3 # 출력층 선형회귀 값 Z3
y = A3 = tf.nn.softmax(Z3) # 출력층 출력 값 A3

In [37]:
# 손실함수 계산 및 가중치 / 바이어스 업데이트(그림 ⑤)
cross_entropy = tf.nn.softmax_cross_entropy_with_logits_v2(logits=Z3, labels=T)
loss = tf.reduce_mean(cross_entropy)
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(loss)

In [38]:
# 정확도 검증 노드 accuracy
predicted_val = tf.equal( tf.argmax(A3, 1), tf.argmax(T, 1) )
accuracy = tf.reduce_mean(tf.cast(predicted_val, dtype=tf.float32))

In [42]:
# MNIST 인식 정확도 검증
with tf.Session() as sess: 
    sess.run(tf.global_variables_initializer()) 
    for I in range(epochs):
        total_batch = int(mnist.train.num_examples / batch_size) # 55,000 / 100
        for step in range(total_batch):
            batch_x, batch_t = mnist.train.next_batch(batch_size)
            loss_val, _ = sess.run([loss, train], feed_dict={X: batch_x, T: batch_t}) 
            if step % 100 == 0:
                print("step = ", step, ", loss_val = ", loss_val)
        # Accuracy 확인
        test_x_data = mnist.test.images
        test_t_data = mnist.test.labels
        accuracy_val = sess.run(accuracy, feed_dict={X: test_x_data, T: test_t_data})
        print("\n", I, "epochs =>", "Accuracy =", accuracy_val)

step =  0 , loss_val =  81.9121
step =  100 , loss_val =  2.6665711
step =  200 , loss_val =  3.7022698
step =  300 , loss_val =  2.054959
step =  400 , loss_val =  1.2035393
step =  500 , loss_val =  1.4928669

 0 epochs => Accuracy = 0.8587
step =  0 , loss_val =  2.6863978
step =  100 , loss_val =  0.9652569
step =  200 , loss_val =  0.95369196
step =  300 , loss_val =  0.61065733
step =  400 , loss_val =  1.5749723
step =  500 , loss_val =  0.50185883

 1 epochs => Accuracy = 0.8776
step =  0 , loss_val =  0.47689098
step =  100 , loss_val =  1.0448676
step =  200 , loss_val =  0.916765
step =  300 , loss_val =  0.6481647
step =  400 , loss_val =  1.3291762
step =  500 , loss_val =  0.65197974

 2 epochs => Accuracy = 0.8801
step =  0 , loss_val =  0.61188513
step =  100 , loss_val =  1.0283322
step =  200 , loss_val =  0.54191226
step =  300 , loss_val =  1.0363463
step =  400 , loss_val =  0.41843995
step =  500 , loss_val =  0.39739022

 3 epochs => Accuracy = 0.8821
step =  0 ,

step =  0 , loss_val =  0.17344345
step =  100 , loss_val =  0.1057163
step =  200 , loss_val =  0.12148061
step =  300 , loss_val =  0.07033768
step =  400 , loss_val =  0.18387277
step =  500 , loss_val =  0.14287299

 33 epochs => Accuracy = 0.9366
step =  0 , loss_val =  0.25149652
step =  100 , loss_val =  0.19192211
step =  200 , loss_val =  0.2880381
step =  300 , loss_val =  0.20192523
step =  400 , loss_val =  0.29733956
step =  500 , loss_val =  0.05285909

 34 epochs => Accuracy = 0.9374
step =  0 , loss_val =  0.17097576
step =  100 , loss_val =  0.056909192
step =  200 , loss_val =  0.27406797
step =  300 , loss_val =  0.23103122
step =  400 , loss_val =  0.035967447
step =  500 , loss_val =  0.16863893

 35 epochs => Accuracy = 0.9387
step =  0 , loss_val =  0.22222409
step =  100 , loss_val =  0.13556299
step =  200 , loss_val =  0.12534048
step =  300 , loss_val =  0.12700419
step =  400 , loss_val =  0.056218248
step =  500 , loss_val =  0.120031826

 36 epochs => Accu

step =  0 , loss_val =  0.11276443
step =  100 , loss_val =  0.12048667
step =  200 , loss_val =  0.10659831
step =  300 , loss_val =  0.0475947
step =  400 , loss_val =  0.12463852
step =  500 , loss_val =  0.12724681

 66 epochs => Accuracy = 0.9466
step =  0 , loss_val =  0.08779521
step =  100 , loss_val =  0.19287929
step =  200 , loss_val =  0.2594186
step =  300 , loss_val =  0.09055048
step =  400 , loss_val =  0.23535997
step =  500 , loss_val =  0.13213588

 67 epochs => Accuracy = 0.9485
step =  0 , loss_val =  0.039856542
step =  100 , loss_val =  0.084652424
step =  200 , loss_val =  0.085592985
step =  300 , loss_val =  0.11958253
step =  400 , loss_val =  0.09592975
step =  500 , loss_val =  0.08330326

 68 epochs => Accuracy = 0.9467
step =  0 , loss_val =  0.098542765
step =  100 , loss_val =  0.15914267
step =  200 , loss_val =  0.33771786
step =  300 , loss_val =  0.052750424
step =  400 , loss_val =  0.15128757
step =  500 , loss_val =  0.09535722

 69 epochs => Acc

step =  500 , loss_val =  0.019007873

 98 epochs => Accuracy = 0.9503
step =  0 , loss_val =  0.0642336
step =  100 , loss_val =  0.08917993
step =  200 , loss_val =  0.100180596
step =  300 , loss_val =  0.15634425
step =  400 , loss_val =  0.1067873
step =  500 , loss_val =  0.11233439

 99 epochs => Accuracy = 0.9499
